//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectAnalisis.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class USAIDEntities1 : DbContext
    {
        public USAIDEntities1()
            : base("name=USAIDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiario> Beneficiario { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<ServicioFormacion> ServicioFormacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<BeneficiarioAnio_Result> BeneficiarioAnio(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BeneficiarioAnio_Result>("BeneficiarioAnio", yearParameter);
        }
    
        public virtual ObjectResult<BeneficiarioCiudad_Result> BeneficiarioCiudad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BeneficiarioCiudad_Result>("BeneficiarioCiudad");
        }
    
        public virtual ObjectResult<BeneficiarioSemestral_Result> BeneficiarioSemestral(Nullable<int> year, Nullable<int> sem)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var semParameter = sem.HasValue ?
                new ObjectParameter("sem", sem) :
                new ObjectParameter("sem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BeneficiarioSemestral_Result>("BeneficiarioSemestral", yearParameter, semParameter);
        }
    
        public virtual ObjectResult<BeneficiariosUsuario_Result> BeneficiariosUsuario(Nullable<int> year, Nullable<int> month)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BeneficiariosUsuario_Result>("BeneficiariosUsuario", yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<psBeneficiarios_Result> psBeneficiarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<psBeneficiarios_Result>("psBeneficiarios");
        }
    
        public virtual ObjectResult<psEmpleados_Result> psEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<psEmpleados_Result>("psEmpleados");
        }
    
        public virtual ObjectResult<psServicioFormacion_Result> psServicioFormacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<psServicioFormacion_Result>("psServicioFormacion");
        }
    
        public virtual ObjectResult<psUsuario_Result> psUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<psUsuario_Result>("psUsuario");
        }
    }
}
